name: Pop Champagne for Lauren & Shane
markdown: redcarpet
pygments: true
permalink: none
url: http://localhost:4000/
exclude: [ assets/sass, node_modules, fed-init.sh, Gemfile, Gemfile.lock, gulp_config.js, gulp_config.sh, Gulpfile.js, package.json, test-results ]